package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Test todomvc")
    void generatedTest() {
        step("open 'https://todomvc.com/examples/emberjs/'", () -> {
            step("// todo: just add selenium action");
        });

        step("add 'a'", () -> {
            step("// todo: just add selenium action");
        });

        step("add 'b'", () -> {
            step("// todo: just add selenium action");
        });

        step("add 'c'", () -> {
            step("// todo: just add selenium action");
        });

        step("edit 'b' to 'b edited'", () -> {
            step("// todo: just add selenium action");
        });

        step("delete 'c'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://todomvc.com/examples/emberjs/'", () ->
            open("https://todomvc.com/examples/emberjs/"));

        step("Page title should have text 'Ember TodoMVC'", () -> {
            String expectedTitle = "Ember TodoMVC";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://todomvc.com/examples/emberjs/'", () ->
            open("https://todomvc.com/examples/emberjs/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}